### ISSUE TITLE
Strange formatting on Tuestday in Followup (?!) 

### ISSUE THREAD

**Issue by victornoel** [albinscode/atgenerator#3]
Hi,

I noticed something strange: during the last week of December, I had only vacations day, and on everyday the data is ok, but on Tuesday, it is written:
```
0conges
```

On other weeks were everything is ok (there is 7h12 in each cell), but only on the Tuesday, the text is underlined by the orthographic corrector…

So I'm not sure if the error is coming from the ods template or from the code :)

**Comment by albinscode** [comment]
Reproduced, come from code ;)
A bad sum was done with an integer and a string! Due to bad initialization...
In test.
